### ISSUE TITLE
Provide Andrea and Harper access to https://services.wim.usgs.gov/krigservices

### ISSUE THREAD

**Issue by amedenblik** [USGS-WiM/streamest#9]
Users are reporting errors with the Streamest application. We think this may be due to an issue with the services at https://services.wim.usgs.gov/krigservices, but Harper and I do not know how to access them. Can you please provide access?

**Comment by harper-wavra** [comment]
It would also be helpful to get access to the S3 bucket wim.usgs.gov in AWS, which is where StreamEst is hosted.

**Comment by aaronstephenson** [comment]
I created an IAM user for both of you in the AWS WIM Main Subaccount, so you have access to the "wim.usgs.gov" S3 bucket.

I also created a WIMCLOUD AD user for both of you in the AWS WIM Main subaccount. I only realized after I created them that you don't need them for this particular task, but they will doubtless be useful in the future. Please change the password immediately after logging in.

I also created a local Windows user for both of you on Toad in the AWS WIM Production Subaccount. This is the server hosting the "services.wim.usgs.gov" web services. Please change the password immediately after logging in.
